### PR TITLE
feat: add ExcludeMethod options with default

### LINKED ISSUE #7: Whitelist marshaler methods
Hi,

as I know,  implementing `encoding.TextUnmarshaler`, `json.Unmarshaler` and `json.Marshaler`, `encoding.TextMarshaler` on the same struct always result into mixed receiver type.

The code inside go tests following the same pattern

* https://github.com/golang/go/blob/583d750fa119d504686c737be6a898994b674b69/src/encoding/json/example_marshaling_test.go#L22-L51
* https://github.com/golang/go/blob/583d750fa119d504686c737be6a898994b674b69/src/encoding/json/example_text_marshaling_test.go#L22-L45

Which leads me into a situation where this is expected and should be not reported.

Ref: https://youtrack.jetbrains.com/issue/GO-13587

### PR DESCRIPTION
**Pull request by raeperd**
## Changed
- Add filtering logic based on method signatures
- Add default method signatures for encoding/marshaling parts of standard libraries 
    - https://github.com/raeperd/recvcheck/issues/7#issuecomment-2468624471
- Add Config, NewAnalyzer function 
    - referenced [alingse/asasalint](https://github.com/alingse/asasalint)
    - user can pass extra signatures in form of `UnmarshalJSON(data []byte, v any) error` 

## Considerations
- check only names not signature? name check can be added later, so check signature in this pr
- runWithFilter is good pattern? tried to be as simple as possible without custom structs 

## next todos
1. Add check for simple method name check, so that user can simply add name of methods 
2. Add README for options

Fixes #7

### CODE REVIEW

**Comment by ldez** [comment]
The signatures of the SQL elements are too "generic" (`Value() (any, error)`) and it can lead to false negatives (some methods will be ignored, but they should not).

I understand you are trying to create something strict and configurable, but I think the full signature approach is a bit overkill, at least as a first step.

For me, the option is a bit weird: either it is an exception, then it can be managed with the exclusions inside golangci-lint, or this a common interface, and then it should be integrated internally (if possible).

Also, the option can lead to false negatives: a signature can be the same between different methods but those methods are related to different structures.

For me, the first step could be to not provide options, and filter on method names internally.


```go
names := []string{
	"MarshalText",
	"MarshalJSON",
	"MarshalXML",
	"MarshalYAML",
	"MarshalBinary",
	"GobEncode",
}

for _, name := range names {
	if funcDecl.Name.Name == name {
		return
	}
}
```

This will reduce the majority of false positives, and for the other cases, classic exclusions for the type inside golangci-lint can be enough.

```yml
issues:
  exclude-rules:
    - path: myfile.go
      text: 'the methods of "Foo" use pointer receiver and non-pointer receiver.'
      linters:
        - recvcheck
```

---

If you want to add an option, I think something simple can be used: struct name + method name (ex: `Foo.Value`).
This is less "generic" but easier to configure than the signature for a user and more strict.

```go
typeName := recvTypeName(funcDecl.Recv.List[0].Type)
```

```go
func recvTypeName(r ast.Expr) string {
	switch n := r.(type) {
	case *ast.Ident:
		return n.Name

	case *ast.StarExpr:
		return recvTypeName(n.X)
	}

	return ""
}
```

---

WDYT?

**Comment by raeperd** [comment]
@ldez 
Thanks for the detailed review!

I agree that checking the method signature is somewhat overkill for most users.

The idea of struct name and method name configuration is a good one. It’s much more usable than the full signature approach. (Maybe we can add this to the next PR.)

I’ll fix this PR with the following changes:
- Check only the default method names in slices.
- Remove the Setting.ExcludeMethod option and leave the NoBuiltinExcludeMethod option.
- Remove the `Value` function from the default.

**Comment by raeperd** [comment]
@ldez 
Can we merge this now? lgtm

**Review by ldez — APPROVED** [review]
LGTM

**Pull request merged**
